---
name: Kocom Wallpad with RS485
version: 2025.12.24
slug: kocom
description: Kocom Wallpad for Home Assistant
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/clipman/HomeAssistant
startup: application
boot: auto
uart: true
map:
  - share:rw
options:
  share/kocom.cfg 설정파일: true
schema:
  share/kocom.cfg 설정파일: bool
